### ISSUE TITLE
Failures cause the runner to hang in ruby 3.2

### ISSUE THREAD

**Issue by thatsmydoing** [ioquatix/turbo_test#10]
In ruby 3.2, if any test fails, the entire runner hangs and never exits.

I also tried adding it to the test matrix and it also hangs there https://github.com/thatsmydoing/turbo_test/actions/runs/4924094038/jobs/8796711346

**Comment by thatsmydoing** [comment]
It seems this is fixed with newer `async`. It's fixed in at least 2.6.1 (and was broken as of 2.5.0)

**Comment by ioquatix** [comment]
Thanks, yes, there have been some internal improvements to the reactor termination process. I'll probably need to circle back to this issue and confirm it's fixed correctly, but I'm glad to hear it's now working as expected.
