### ISSUE TITLE
Adding by default to rspec?

### ISSUE THREAD

**Issue by benoittgt** [ioquatix/turbo_test#3]
Hello Samuel 😊

I am wondering if your work could be added to rspec itself not as a dependency?

PS: I didn't start to read the project's code.

Thanks for your work.

**Comment by ioquatix** [comment]
Thanks for your feedback.

That's possible, but I think it depends on RSpec maintainers.

This code is actually test framework agnostic - it should be fairly easy to add support for other test frameworks.

**Comment by benoittgt** [comment]
@JonRowe  and @pirj what do you think?

**Comment by pirj** [comment]
To me, it would be reasonable to include the part that consumes examples from an external queue.

Wondering if the impact of this would be minimal with pipes, e.g.
Syntetic:
```
rspec < <(echo spec/example1_spec.rb; sleep 1; echo spec/example2_spec.rb)
```
Real-ish:
```
rspec < <(queue-client)
```

**Comment by ioquatix** [comment]
There are several issues with RSpec which could be addressed to make it more easy to:

- Isolate global state.
- Serialize results and aggregate results.
- Better handling of signals.

Maybe the queue abstraction would be the first step in this direction.

**Comment by pirj** [comment]
> Isolate global state

@ioquatix Do you have something specific in mind?
Theadsafe for `let` is [on by default](https://github.com/rspec/rspec-core/blob/ecb65d2d4ea7b381472e3084f45e2da94e00ce91/lib/rspec/core/configuration.rb#L557), [`RSpec.current_example` uses `Thread.local`](https://github.com/rspec/rspec-core/blob/fe3084758857f0714f05ada44a18f1dfe9bf7a7e/lib/rspec/core.rb#L122). @JonRowe what were your findings?

Surely in-process "parallelization" would be more efficient, but it's a different concern.

Also, using *nix pipes as our transport implies we parallelize with processes, right? We don't have to consider thread safety, or should we?

> Serialize results and aggregate results

:+1: This is trivial as far as I recall. This is not load-intensive, so we can add mutex locking to Reported, that should do it?

> Better handling of signals

What do you have in mind specifically? As I imagine it with pipes, and even more that with TCP sockets, there won't be any option to send signals from the queue process and workers.

**Comment by ioquatix** [comment]
Here are the problems: https://github.com/ioquatix/turbo_test/blob/master/lib/turbo_test/rspec/job.rb#L66-L84
